<a href="https://colab.research.google.com/github/seungeunlee00/AI/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The Numpy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays

In [1]:
import numpy as np

Initial Placeholders

In [17]:
#asking for help
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [6]:
np.zeros((3,4)) #create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2,3,4),dtype=np.int16) #create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [44]:
d=np.arange(10,25,5) #create an array of evenly spaced values (step value)
print(d)

[10 15 20]


In [10]:
np.linspace(0,2,9) #create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [45]:
e=np.full((2,2),7) #create a constant array 
print(e)

[[7 7]
 [7 7]]


In [46]:
f=np.eye(2) #create a 2X2 identity matrix
print(f)

[[1. 0.]
 [0. 1.]]


In [13]:
np.random.random((2,2)) #create an array with random values

array([[0.03116077, 0.69615764],
       [0.9918538 , 0.813011  ]])

In [14]:
np.empty((3,2)) #create an empty array

array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

Creating Arrays

In [16]:
a=np.array([1,2,3])
b=np.array([(1.5,2,3), (4,5,6)], dtype=float)
c=np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype=float)

Saving & Loading on disk


In [ ]:
np.save('my_array', a)
np.savez('array,npz', a, b)
np.load('my_array.npy')

Saving & Loading text files

In [ ]:
np.loadtxt("myfile.txt")
np.genfromtxt("my_file.csv", delimiter=',')
np.savetxt("myarray.txt", a, delimiter=' ')

Inspecting Your Array

In [18]:
a.shape #array dimensions

(3,)

In [19]:
len(a) #length of array

3

In [20]:
b.ndim #number of array dimensions

2

In [21]:
a.size #number of array elements

3

In [22]:
b.dtype #data type of array elements

dtype('float64')

In [23]:
b.dtype.name #name of data type

'float64'

In [24]:
b.astype(int) #convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

Data Types

In [26]:
np.int64 #signed 64-bit integer types
np.float32 #standard double-precision floating point
np.complex #complex numbers represented by 128 floats
np.bool #boolean type storing TRUE and FALSE values
np.object #pythono object type
np.string_ #fixed-length string type
np.unicode_ #fixed-length unicode type

<ipython-input-26-fcdc3d505ae0>:3: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.complex #complex numbers represented by 128 floats
<ipython-input-26-fcdc3d505ae0>:4: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool #boolean type storing TRUE and FALSE values
<ipython-input-26-fcdc3d505ae0>:5: DeprecationWarning: `np.object` i

numpy.bytes_

Array Mathematics

Arithmetic Operations

In [30]:
print(a-b) #subtraction
np.subtract(a,b) 

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [32]:
print(b+a) #addition
np.add(b,a) 

[[2.5 4.  6. ]
 [5.  7.  9. ]]


array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [34]:
print(a/b) #division
np.divide(a,b)

[[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]]


array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [35]:
print(a*b) #multiplication
np.multiply(a,b)

[[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]


array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [36]:
np.exp(b) #exponentiation

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [38]:
np.sqrt(b) #square root

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [39]:
np.sin(a) #print sines of an array

array([0.84147098, 0.90929743, 0.14112001])

In [40]:
np.cos(a) #element-wise cosine

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [41]:
np.log(a) #element-wise natural logarithm

array([0.        , 0.69314718, 1.09861229])

In [47]:
e.dot(f) #dot product

array([[7., 7.],
       [7., 7.]])

Comparison

In [48]:
a==b #element-wise comparison

array([[False,  True,  True],
       [False, False, False]])

In [49]:
a<2 #element-wise comparison

array([ True, False, False])

In [50]:
np.array_equal(a,b) #array-wise comparison

False

Aggregate Functions

In [51]:
a.sum() #array-wise sum

6

In [52]:
a.min() #array-wise minimum value

1

In [53]:
b.max(axis=0) #maximum value of an array row

array([4., 5., 6.])

In [54]:
b.cumsum(axis=1) #cumulative sum of the elements

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [55]:
a.mean() #mean

2.0

In [56]:
np.median(b) #median

3.5

In [57]:
np.corrcoef(a) #correlation coefficient

1.0

In [58]:
np.std(b) #standard deviation

1.5920810978785667

Copying Arrays

In [61]:
h=a.view() #create a view of the array with the same data
print(h)

[1 2 3]


In [60]:
np.copy(a) #create a copy of the array

array([1, 2, 3])

In [63]:
h=a.copy() #create a deep copy of the array
print(h)

[1 2 3]


Sorting Arrays

In [65]:
a.sort() #sort an array
print(a)

[1 2 3]


In [67]:
c.sort(axis=0) #sort the elements of an array's axis
print(c)

[[[1.5 2.  1. ]
  [4.  5.  6. ]]

 [[3.  2.  3. ]
  [4.  5.  6. ]]]
[[[1.5 2.  1. ]
  [4.  5.  6. ]]

 [[3.  2.  3. ]
  [4.  5.  6. ]]]


Subsetting

In [68]:
a[2] #select the element at the 2nd index

3

In [69]:
b[1,2] #select the element at row 1 column 2 (equivalent to b[1][2])

6.0

Slicing

In [70]:
a[0:2] #select items at index 0 and 1

array([1, 2])

In [71]:
b[0:2, 1] #select item at rows 0 and 1 in column 1

array([2., 5.])

In [72]:
b[:1] #select all items at row 0 (equivalent to b[0:1, :])

array([[1.5, 2. , 3. ]])

In [73]:
c[1, ...] #same as [1, :, :]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [74]:
a[ : :-1] #reversed array a array([3,2,1])

array([3, 2, 1])

Boolean Indexing

In [75]:
a[a<2] #select elements from a less than 2

array([1])

Fancy Indexing

In [76]:
b[[1,0,1,0], [0,1,2,0]] #select elements (1,0),(0,2),(1,2) and (0,0)

array([4. , 2. , 6. , 1.5])

In [77]:
b[[1,0,1,0]][:,[0,1,2,0]] #select a subset of the matrix's row and columns

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

Array Manipulation

Transposing Array

In [78]:
i=np.transpose(b) #permute array dimensions
i.T #permute array dimensions

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Changing Array Shape

In [80]:
b.ravel() #flatten the array

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [81]:
g.reshape(3,-2) #reshape, but don't change data

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

Adding/Removind Elements

In [86]:
np.resize(h, (2,6)) #return a new array with shape (2,6)

[1 2 3]


array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [87]:
np.append(h,g) #append items to an array

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [90]:
print(a)
np.insert(a,1,5) #insert items in an array

[1 2 3]


array([1, 5, 2, 3])

In [89]:
np.delete(a,[1])

array([1, 3])

Combining Arrays

In [91]:
np.concatenate((a,d), axis=0) #concatenate arrays

array([ 1,  2,  3, 10, 15, 20])

In [92]:
np.vstack((a,b)) #stack arrays vertically (row-wise)

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [93]:
np.r_[e,f] #stack arrays vertically (row-wise)

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [94]:
np.hstack((e,f)) #stack arrays horizontally (column-wise)

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [95]:
np.column_stack((a,d)) #create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [96]:
np.c_[a,d] #create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

Splitting Arrays

In [97]:
np.hsplit(a,3) #split the array horizontally at the 3rd index

[array([1]), array([2]), array([3])]

In [98]:
np.vsplit(c,2) #split the array vertically at the 2nd index

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [4., 5., 6.]]])]